# Generated by Django 3.0.3 on 2020-02-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='department',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.PositiveIntegerField(max_length=10, null=True),
        ),
    ]
