# Generated by Django 3.0.3 on 2020-02-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200209_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.PositiveIntegerField(max_length=10, null=True, verbose_name='موبایل'),
        ),
    ]
