# Generated by Django 3.0.3 on 2020-02-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200209_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.PositiveIntegerField(null=True, verbose_name='موبایل'),
        ),
    ]
