# Generated by Django 3.0.3 on 2020-02-07 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('admin_id', models.IntegerField(blank=True, null=True)),
                ('admin_user', models.CharField(max_length=50, null=True)),
                ('chat_title', models.CharField(blank=True, max_length=50)),
                ('chat_username', models.CharField(max_length=50)),
                ('phone', models.IntegerField(null=True)),
                ('date_purchased', models.DateField(auto_now_add=True)),
                ('is_purchased', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Senf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(blank=True, null=True)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(max_length=5000, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Channel')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='saletype',
            field=models.ManyToManyField(to='bot.SaleType'),
        ),
        migrations.AddField(
            model_name='channel',
            name='senf',
            field=models.ManyToManyField(to='bot.Senf'),
        ),
        migrations.AddField(
            model_name='channel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
